version: "3.8"
volumes:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - ${WEB_PORT:-3000}:3000
    volumes:
      - ./backend:/work/backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - PROJECT_NAME=${PROJECT_NAME:-graphql-example}
    depends_on:
      - db
    stdin_open: true

  db:
    image: postgres:13.1-alpine
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
