name: Ruby Test

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install dependencies
        run: bundle install
        working-directory: ./backend
      - name: Run tests
        run: rails t
        working-directory: ./backend
